name: Publish to pages
on:
  push:
    branches: 
      - master

jobs:
  build:
      name: jekyll-deploy-gh-pages
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
          with:
            ref: master
        - name: jekyll-deploy-gh-pages
          uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
          env:
            GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      
